language: ruby
rvm:
  - 1.9.2
  - 1.8.7
notifications:
  recipients:
    - roland.swingler@gmail.com
branches:
  only:
    - master
before_script: export RUBY_FFI_NCURSES_LIB=/lib/x86_64-linux-gnu/libncursesw.so.5