language: ruby
rvm:
  - 1.9.2
  - 1.8.7
notifications:
  recipients:
    - roland.swingler@gmail.com
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install libncurses5-dev libncursesw5-dev lib32ncursesw5-dev
